# Generated by Django 3.2.5 on 2022-06-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wac',
            old_name='h_geocode',
            new_name='w_geocode',
        ),
    ]
