# Generated by Django 3.2.5 on 2022-06-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0005_auto_20220609_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoBG_2019',
        ),
        migrations.DeleteModel(
            name='GeoBlocks_2019',
        ),
        migrations.DeleteModel(
            name='GeoTracts_2019',
        ),
    ]
