# Generated by Django 3.2.5 on 2022-06-09 19:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0012_auto_20220609_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoBG_2019',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATEFP', models.CharField(max_length=2)),
                ('COUNTYFP', models.CharField(max_length=3)),
                ('TRACTCE', models.CharField(max_length=6)),
                ('GEOID', models.CharField(max_length=12)),
                ('MTFCC', models.CharField(max_length=5)),
                ('FUNCSTAT', models.CharField(max_length=1)),
                ('ALAND', models.IntegerField()),
                ('AWATER', models.IntegerField()),
                ('INTPTLAT', models.FloatField()),
                ('INTPTLON', models.FloatField()),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('NAMELSAD', models.CharField(max_length=19)),
                ('BLKGRPCE', models.CharField(max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeoBlocks_2019',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATEFP', models.CharField(max_length=2)),
                ('COUNTYFP', models.CharField(max_length=3)),
                ('TRACTCE', models.CharField(max_length=6)),
                ('GEOID', models.CharField(max_length=12)),
                ('MTFCC', models.CharField(max_length=5)),
                ('FUNCSTAT', models.CharField(max_length=1)),
                ('ALAND', models.IntegerField()),
                ('AWATER', models.IntegerField()),
                ('INTPTLAT', models.FloatField()),
                ('INTPTLON', models.FloatField()),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('NAME', models.CharField(max_length=10)),
                ('UR', models.CharField(max_length=1)),
                ('UACE', models.CharField(max_length=5)),
                ('UATYPE', models.CharField(max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeoTracts_2019',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATEFP', models.CharField(max_length=2)),
                ('COUNTYFP', models.CharField(max_length=3)),
                ('TRACTCE', models.CharField(max_length=6)),
                ('GEOID', models.CharField(max_length=12)),
                ('MTFCC', models.CharField(max_length=5)),
                ('FUNCSTAT', models.CharField(max_length=1)),
                ('ALAND', models.IntegerField()),
                ('AWATER', models.IntegerField()),
                ('INTPTLAT', models.FloatField()),
                ('INTPTLON', models.FloatField()),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('NAMELSAD', models.CharField(max_length=19)),
                ('NAME', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
