# Generated by Django 3.2.5 on 2022-06-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0015_geobg_2019_geoblocks_2019_geotracts_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoblocks_2019',
            name='UACE',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='geoblocks_2019',
            name='UATYPE',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
    ]
